services:
  system-restore-toolkit:
    build:
      context: .
      dockerfile: Dockerfile
    image: system-restore-toolkit:latest
    container_name: restore-toolkit
    privileged: true  # Required for LVM operations and host access
    restart: unless-stopped
    pid: host  # Access to host process namespace for nsenter
    
    volumes:
      # Mount host filesystem for backup operations
      - /:/host:rw
      # Persistent storage for backups
      - ./backups:/var/backups/system-restore-toolkit
      # Persistent storage for logs
      - ./logs:/var/log/system-restore-toolkit
      # Docker socket (if needed for container operations)
      - /var/run/docker.sock:/var/run/docker.sock
      # Host system information access
      - /etc/hostname:/host/etc/hostname:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/lsb-release:/host/etc/lsb-release:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
    
    environment:
      - TZ=UTC
      - BACKUP_RETENTION_DAYS=30
      - LOG_LEVEL=INFO
    
    # Keep container running
    tty: true
    entrypoint: [""]
    command: ["tail", "-f", "/dev/null"]
    stdin_open: true
    
    networks:
      - toolkit-network

  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    image: system-restore-toolkit-web:latest
    container_name: restore-toolkit-web
    restart: unless-stopped
    privileged: true  # For hardware access
    pid: host  # Access to host process namespace for nsenter
    
    ports:
      - "5000:5000"
    
    volumes:
      # Access to toolkit scripts and logs
      - .:/toolkit:ro
      - ./logs:/toolkit/logs:ro
      - ./backups:/toolkit/backups:ro
      # Host system information access
      - /etc/hostname:/host/etc/hostname:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/lsb-release:/host/etc/lsb-release:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      # Mount entire host filesystem for chroot access
      - /:/host:rw
    
    environment:
      - TZ=UTC
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_DEV=/host/dev
      - HOST_ETC=/host/etc
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility,compute
    
    runtime: nvidia
    
    depends_on:
      - system-restore-toolkit
    
    networks:
      - toolkit-network
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.restore-toolkit-web.rule=Host(`restore-toolkit.local`)"
      - "traefik.http.services.restore-toolkit-web.loadbalancer.server.port=5000"

volumes:
  toolkit-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backups
      
  toolkit-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

networks:
  toolkit-network:
    name: system-restore-toolkit-network
    driver: bridge
