name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t system-restore-toolkit:test .
      
    - name: Test Docker image
      run: |
        docker run --rm system-restore-toolkit:test help
        docker run --rm system-restore-toolkit:test disk-usage
        
    - name: Test installation script
      run: |
        chmod +x install.sh
        ./install.sh --check
